version: "3.3"
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www/:/usr/share/nginx/html/
    ports: 
      - 80:80
    restart: always

  toto_db:
    env_file:
      - db.env
    image: postgres:9.4
    ports:
      - 5432:5432
  
  tata_db:
    env_file:
      - db.env
    image: postgres:9.4
    ports:
      - 5433:5432
